# Generated by Django 5.1 on 2024-09-18 09:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manager', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('seat_number', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('alighting_stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alighting_tickets', to='manager.stage')),
                ('boarding_stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boarding_tickets', to='manager.stage')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='manager.car')),
                ('cashier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='manager.route')),
            ],
            options={
                'unique_together': {('car', 'seat_number', 'created_at')},
            },
        ),
    ]
