# Generated by Django 5.1 on 2024-09-18 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='name',
            field=models.CharField(default='name', max_length=100),
        ),
        migrations.AddField(
            model_name='ticket',
            name='number',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
