# Generated by Django 5.1 on 2024-09-18 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0002_ticket_name_ticket_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Mpesa', 'Mpesa')], default='money', max_length=100),
        ),
    ]
