# Generated by Django 5.1 on 2024-09-18 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0004_remove_ticket_boarding_stage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='cashier',
        ),
    ]
