# Generated by Django 5.2.1 on 2025-08-14 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0006_rename_number_ticket_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='id',
            field=models.CharField(default='T1905251', max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
