# Generated by Django 5.1 on 2024-09-04 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='route_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.route'),
        ),
        migrations.AddField(
            model_name='route',
            name='stage_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.stage'),
        ),
    ]
