# Generated by Django 5.1 on 2024-09-09 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='stage',
            field=models.ManyToManyField(related_name='routes', to='manager.stage'),
        ),
    ]
