# Generated by Django 5.1 on 2024-09-09 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_stageprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='route_price',
        ),
        migrations.AlterField(
            model_name='stageprice',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_prices', to='manager.route'),
        ),
        migrations.AlterField(
            model_name='stageprice',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_prices', to='manager.stage'),
        ),
    ]
